spring.application.name=PostClientService
server.port=8081

post.client.base-url=http://localhost:8080/api
post.client.user-url=http://localhost:8080/api/user
post.client.login-url=http://localhost:8080/api/auth/login
post.client.registration-url=http://localhost:8080/api/auth/registration
post.client.posts-url=http://localhost:8080/api/posts
post.client.commentaries-url=http://localhost:8080/api/commentaries
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB