spring.application.name=PostClientService

server.port=${PORT:8081}

post.client.base-url=${POST_REST_API_BASE_URL:https://post-rest-api-nev6.onrender.com/api}

post.client.user-url=${post.client.base-url}/user
post.client.login-url=${post.client.base-url}/auth/login
post.client.registration-url=${post.client.base-url}/auth/registration
post.client.posts-url=${post.client.base-url}/posts
post.client.commentaries-url=${post.client.base-url}/commentaries

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:10MB}

spring.thymeleaf.cache=true

logging.level.org.springframework.web=${SPRING_WEB_LOG_LEVEL:INFO}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:INFO}